---
pack_pattern:   ddddddddB
header_size:    4
fields:
    - timestamp
    - latitude
    - longitude
    - altitude
    - speed
    - bearing
    - horizontal_accuracy
    - vertical_accuracy
    - source

# Formats and templates
# default
output_format: csv
templates:
    header:
        csv:    "timestamp,latitude,longitude,altitude,speed,bearing,horizontal_accuracy,vertical_accuracy,source\n"
        tab:    "timestamp\tlatitude\tlongitude\taltitude\tspeed\tbearing\thorizontal_accuracy\tvertical_accuracy\tsource\n"
        gpx:    >
            <?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
            <gpx version="1.1" creator="read-mapsme-track" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
              <trk>
                <trkseg>
    row:
        csv:    "{timestamp},{latitude},{longitude},{altitude},{speed},{bearing},{horizontal_accuracy},{vertical_accuracy},{source}\n"
        tab:    "{timestamp}\t{latitude}\t{longitude}\t{altitude}\t{speed}\t{bearing}\t{horizontal_accuracy}\t{vertical_accuracy}\t{source}\n"
        gpx:    >
                  <trkpt lat="{latitude}" lon="{longitude}">
                    <ele>{altitude}</ele>
                    <hdop>{horizontal_accuracy}</hdop>
                    <vdop>{vertical_accuracy}</vdop>
                    <time>{timestamp}</time>
                    <!--extensions>
                      <course>{bearing}<course>
                      <speed>{speed}</speed>
                    </extensions-->
                  </trkpt>
    footer:
        csv:    ""
        tab:    ""
        gpx:    >
                </trkseg>
                </trk>
                </gpx>
